package com.example.aifactory.scm.service;

import com.example.aifactory.scm.config.ScmDeliveryProperties;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import tools.jackson.databind.JsonNode;

import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.PosixFilePermissions;
import java.time.Duration;
import java.util.List;
import java.util.Map;

@Service
public class GiteaDeliveryBackend implements ScmDeliveryBackend {
    private final ScmDeliveryProperties properties;
    private final ScmCredentials credentials;
    private final WebClient client;

    public GiteaDeliveryBackend(ScmDeliveryProperties properties, ScmCredentials credentials, WebClient.Builder builder) {
        this.properties = properties;
        this.credentials = credentials;
        this.client = builder.baseUrl(properties.giteaBaseUrl()).build();
    }

    @Override
    public DeliveryResult findExisting(DeliveryCommand command) {
        JsonNode response = client.get()
                .uri(builder -> builder.path("/api/v1/repos/{owner}/{name}/pulls")
                        .queryParam("state", "open")
                        .queryParam("head", command.repository().owner() + ":" + command.branch())
                        .queryParam("base", command.baseBranch())
                        .build(command.repository().owner(), command.repository().name()))
                .header("Authorization", "token " + credentials.giteaToken())
                .retrieve().bodyToMono(JsonNode.class).block(Duration.ofSeconds(20));
        if (response == null || !response.isArray() || response.isEmpty()) {
            return null;
        }
        JsonNode pullRequest = response.get(0);
        String commit = pullRequest.path("head").path("sha").asText();
        if (!commit.matches("[0-9a-f]{40}")) {
            throw new IllegalStateException("existing SCM pull request has no immutable head SHA");
        }
        return new DeliveryResult(command.repository().repositoryId(), command.branch(), commit,
                pullRequest.path("id").asLong(), publicUrl(pullRequest.path("html_url").asText()),
                pullRequest.path("draft").asBoolean(true));
    }

    @Override
    public DeliveryResult createDraftPullRequest(DeliveryCommand command) throws Exception {
        Path askpass = createAskPass(command.taskId());
        try {
            git(command, askpass, "checkout", "-b", command.branch());
            git(command, askpass, "config", "user.email", "ai-factory@example.local");
            git(command, askpass, "config", "user.name", "AI Factory Delivery");
            git(command, askpass, "add", "-A");
            git(command, askpass, "reset", "--", ".ai-plan.md", "changes.patch", ".ai-review.md", ".ai-factory");
            git(command, askpass, "commit", "-m", command.title());
            String commit = git(command, askpass, "rev-parse", "HEAD").strip();
            git(command, askpass, "push", remote(command.repository()), "HEAD:refs/heads/" + command.branch());
            JsonNode response = client.post()
                    .uri("/api/v1/repos/{owner}/{name}/pulls", command.repository().owner(), command.repository().name())
                    .header("Authorization", "token " + credentials.giteaToken())
                    .bodyValue(Map.of("title", command.title(), "head", command.branch(), "base", command.baseBranch(),
                            "body", "Generated by AI Software Factory. Human review required.", "draft", true))
                    .retrieve().bodyToMono(JsonNode.class).block(Duration.ofSeconds(30));
            if (response == null || response.path("id").asLong(0) <= 0 || response.path("html_url").asText().isBlank()) {
                throw new IllegalStateException("SCM pull request response is incomplete");
            }
            return new DeliveryResult(command.repository().repositoryId(), command.branch(), commit,
                    response.path("id").asLong(), publicUrl(response.path("html_url").asText()), true);
        } finally {
            Files.deleteIfExists(askpass);
        }
    }

    private String git(DeliveryCommand command, Path askpass, String... arguments) throws Exception {
        java.util.ArrayList<String> process = new java.util.ArrayList<>(List.of("git"));
        process.addAll(List.of(arguments));
        ProcessBuilder builder = new ProcessBuilder(process).directory(command.workspace().toFile()).redirectErrorStream(true);
        builder.environment().put("GIT_ASKPASS", askpass.toString());
        builder.environment().put("GIT_TERMINAL_PROMPT", "0");
        builder.environment().put("AI_FACTORY_GIT_USER", properties.giteaUser());
        builder.environment().put("AI_FACTORY_GIT_TOKEN", credentials.giteaToken());
        Process child = builder.start();
        String output = new String(child.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
        if (!child.waitFor(2, java.util.concurrent.TimeUnit.MINUTES)) {
            child.destroyForcibly();
            throw new IllegalStateException("SCM git operation timed out");
        }
        if (child.exitValue() != 0) {
            throw new IllegalStateException("SCM git operation failed");
        }
        return output;
    }

    private Path createAskPass(String taskId) throws Exception {
        Path script = Path.of("/tmp", "scm-askpass-" + taskId);
        Files.writeString(script, "#!/bin/sh\ncase \"$1\" in *Username*) printf '%s' \"$AI_FACTORY_GIT_USER\";; *) printf '%s' \"$AI_FACTORY_GIT_TOKEN\";; esac\n");
        Files.setPosixFilePermissions(script, PosixFilePermissions.fromString("rwx------"));
        return script;
    }

    private String remote(RepositoryRegistry.RepositoryDefinition repository) {
        return properties.giteaBaseUrl() + repository.clonePath();
    }

    private String publicUrl(String internalUrl) {
        URI internal = URI.create(internalUrl);
        URI external = URI.create(properties.giteaPublicBaseUrl());
        return URI.create(external.getScheme() + "://" + external.getAuthority() + internal.getRawPath()).toString();
    }
}
