CREATE TABLE a2a_agent_task (
    task_id VARCHAR(64) PRIMARY KEY,
    context_id VARCHAR(64) NOT NULL,
    message_id VARCHAR(128) NOT NULL UNIQUE,
    message_digest CHAR(64) NOT NULL,
    agent_role VARCHAR(64) NOT NULL,
    skill_id VARCHAR(160) NOT NULL,
    caller_subject VARCHAR(200) NOT NULL,
    tenant_id VARCHAR(200) NOT NULL,
    delegation_id VARCHAR(200) NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    task_state VARCHAR(32) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_a2a_agent_task_acl
    ON a2a_agent_task (tenant_id, caller_subject, submitted_at, task_id);
CREATE INDEX idx_a2a_agent_task_context
    ON a2a_agent_task (tenant_id, caller_subject, context_id);

CREATE TABLE a2a_agent_task_history (
    sequence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL REFERENCES a2a_agent_task(task_id) ON DELETE CASCADE,
    message_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    occurred_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_a2a_agent_task_history_task
    ON a2a_agent_task_history (task_id, sequence_id);

CREATE TABLE a2a_agent_task_artifact (
    artifact_id VARCHAR(128) PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL REFERENCES a2a_agent_task(task_id) ON DELETE CASCADE,
    tenant_id VARCHAR(200) NOT NULL,
    acl_subject VARCHAR(200) NOT NULL,
    artifact_digest CHAR(64) NOT NULL,
    artifact_json TEXT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_a2a_agent_task_artifact_acl
    ON a2a_agent_task_artifact (task_id, tenant_id, acl_subject);
