package com.example.aifactory.service;

import com.example.aifactory.config.AiFactoryProperties;
import tools.jackson.databind.JsonNode;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

import java.net.URI;
import java.nio.file.Path;
import java.time.Duration;
import java.util.List;
import java.util.Map;

@Service
public class GiteaService {
    private final AiFactoryProperties props;
    private final ProcessRunner runner;
    private final WebClient client;

    public GiteaService(AiFactoryProperties props, ProcessRunner runner, WebClient.Builder builder) {
        this.props = props;
        this.runner = runner;
        this.client = builder.baseUrl(props.giteaBaseUrl()).build();
    }

    public String commitPushAndCreatePr(Path workspace, String repositoryUrl, String baseBranch, String taskId, String requirement) throws Exception {
        if (props.giteaToken() == null || props.giteaToken().isBlank()) {
            throw new IllegalStateException("GITEA_TOKEN is empty. Generate a token and set it in .env before approval.");
        }
        String branch = "ai-factory/" + taskId;
        runner.run(List.of("git", "checkout", "-b", branch), workspace, Duration.ofSeconds(30));
        runner.run(List.of("git", "config", "user.email", "ai-factory@example.local"), workspace, Duration.ofSeconds(10));
        runner.run(List.of("git", "config", "user.name", "AI Factory Agent"), workspace, Duration.ofSeconds(10));
        runner.run(List.of("git", "add", "-A"), workspace, Duration.ofSeconds(10));
        runner.run(List.of("git", "reset", "--", ".ai-plan.md", "changes.patch", ".ai-review.md", ".ai-factory"), workspace, Duration.ofSeconds(10));
        runner.run(List.of("git", "commit", "-m", "AI Factory: " + abbreviate(requirement, 70)), workspace, Duration.ofSeconds(30));

        URI uri = URI.create(repositoryUrl);
        String authRemote = uri.getScheme() + "://" + props.giteaUser() + ":" + props.giteaToken() + "@" + uri.getHost()
                + (uri.getPort() > 0 ? ":" + uri.getPort() : "") + uri.getPath();
        runner.run(List.of("git", "push", authRemote, "HEAD:refs/heads/" + branch), workspace, Duration.ofMinutes(2));

        String[] parts = uri.getPath().replaceFirst("^/", "").replaceFirst("\\.git$", "").split("/");
        if (parts.length < 2) throw new IllegalArgumentException("Cannot derive owner/repo from " + repositoryUrl);
        String api = "/api/v1/repos/" + parts[0] + "/" + parts[1] + "/pulls";
        JsonNode response = client.post().uri(api)
                .header("Authorization", "token " + props.giteaToken())
                .bodyValue(Map.of(
                        "title", "AI Factory: " + abbreviate(requirement, 90),
                        "head", branch,
                        "base", baseBranch,
                        "body", "Generated by the AI Software Factory prototype. Human review required."))
                .retrieve().bodyToMono(JsonNode.class).block(Duration.ofSeconds(30));
        if (response == null || response.path("html_url").isMissingNode()) return null;
        return publicUrl(response.path("html_url").asText());
    }

    private String publicUrl(String internalUrl) {
        URI internal = URI.create(internalUrl);
        URI external = URI.create(props.giteaPublicBaseUrl());
        return URI.create(external.getScheme() + "://" + external.getAuthority() + internal.getRawPath()
                + (internal.getRawQuery() == null ? "" : "?" + internal.getRawQuery())
                + (internal.getRawFragment() == null ? "" : "#" + internal.getRawFragment())).toString();
    }

    private static String abbreviate(String s, int n) {
        return s == null ? "change" : (s.length() <= n ? s : s.substring(0, n - 3) + "...");
    }
}
